import random
import time

# Emote maps
TOP_10_EMOTES = {
    1: "emote-graceful",
    2: "emote-graceful",
    3: "emote-graceful",
    4: "hcc-jetpack",
    5: "hcc-jetpack",
    6: "emote-headball",
    7: "dance-spiritual",
    8: "dance-spiritual",
    9: "emoji-flex",
    10: "dance-spiritual",
}

FLIRT_EMOTE = "emote-lust"      # Ranks 11–100
FROLIC_EMOTE = "emoji-flex"     # Ranks 101–1000
FLOSS_EMOTE = "dance-floss"     # First-time join


TOP_10_WELCOME_MSGS = {
    1: [
        "👑 Rank #1 - LEGEND @{username} enters the story where hearts pause. 💖",
        "👑 Rank #1 - LEGEND @{username} returns — love trembles with anticipation. 💘",
        "👑 Rank #1 - LEGEND @{username}, the myth every heart remembers. 🔥",
        "👑 Rank #1 - LEGEND @{username} walks in — even silence falls in love. 💫",
        "👑 Rank #1 - LEGEND @{username}, love’s undefeated champion. 🏆",
        "👑 Rank #1 - LEGEND @{username}, where every heartbeat writes poetry. ✍️",
        "👑 Rank #1 - LEGEND @{username}, the spark that started it all. ✨",
        "👑 Rank #1 - LEGEND @{username}, whose name echoes in every love song. 🎶",
        "👑 Rank #1 - LEGEND @{username}, the definition of desire. ❤️‍🔥",
        "👑 Rank #1 - LEGEND @{username}, whose footsteps leave trails of romance. 👣",
        "👑 Rank #1 - LEGEND @{username}, the reason hearts come back. 🔄",
        "👑 Rank #1 - LEGEND @{username}, romance perfected. 💎",
        "👑 Rank #1 - LEGEND @{username}, the storm and the calm. 🌪️🌸",
        "👑 Rank #1 - LEGEND @{username}, written in stars and sealed in kisses. 🌠💋",
        "👑 Rank #1 - LEGEND @{username}, hearts hold their breath. 😮‍💨💘",
        "👑 Rank #1 - LEGEND @{username}, too iconic to ignore. 📸",
        "👑 Rank #1 - LEGEND @{username}, with a presence that bends time. ⌛",
        "👑 Rank #1 - LEGEND @{username}, master of every heartbeat. 💓",
        "👑 Rank #1 - LEGEND @{username}, passion redefined. 🔥",
        "👑 Rank #1 - LEGEND @{username}, love’s final boss. 🎮❤️",
        "👑 Rank #1 - LEGEND @{username}, magnetic and untouchable. 🧲",
        "👑 Rank #1 - LEGEND @{username}, no one arrives like this. 🚪💥",
        "👑 Rank #1 - LEGEND @{username}, the crown was never in question. 👑",
        "👑 Rank #1 - LEGEND @{username}, the mood. Always. 🕶️",
        "👑 Rank #1 - LEGEND @{username}, romance starts when you arrive. 💌",
        "👑 Rank #1 - LEGEND @{username}, a love story no one can top. 🥇",
        "👑 Rank #1 - LEGEND @{username}, sculpted in passion and light. 🗿✨",
        "👑 Rank #1 - LEGEND @{username}, the heart's favorite rumor. 💘👂",
        "👑 Rank #1 - LEGEND @{username}, lighting fire where there was none. 🕯️🔥",
        "👑 Rank #1 - LEGEND @{username}, walking with a crown only love can see. 👑💓",
        "👑 Rank #1 - LEGEND @{username}, every second feels handwritten. ✍️⏳",
        "👑 Rank #1 - LEGEND @{username}, you make the stars jealous. 🌠😌",
        "👑 Rank #1 - LEGEND @{username}, where beauty and bravery hold hands. 🤝",
        "👑 Rank #1 - LEGEND @{username}, chaos and calm in perfect balance. 🌊🕊️",
        "👑 Rank #1 - LEGEND @{username}, the one we all write poems about. 📝❤️",
        "👑 Rank #1 - LEGEND @{username}, every step draws hearts closer. 👣💘",
        "👑 Rank #1 - LEGEND @{username}, the origin of romantic gravity. 🌌",
        "👑 Rank #1 - LEGEND @{username}, the fire in every whisper. 🔥🗣️",
        "👑 Rank #1 - LEGEND @{username}, midnight wrapped in gold. 🌙🏅",
        "👑 Rank #1 - LEGEND @{username}, the voice of a thousand heartbeats. 🎙️💓"
    ],
    2: [
        "👑 Rank #2 - RULER @{username}, the crown may rest elsewhere, but the power is yours. 💥",
        "👑 Rank #2 - RULER @{username} returns — elegance, danger, and desire combined. 🖤",
        "👑 Rank #2 - RULER @{username}, your reign continues with quiet fire. 🔥👑",
        "👑 Rank #2 - RULER @{username}, hearts kneel before your gaze. 💘",
        "👑 Rank #2 - RULER @{username}, walking royalty with lips that command. 👣💋",
        "👑 Rank #2 - RULER @{username}, love bends when you speak. 🗣️❤️",
        "👑 Rank #2 - RULER @{username}, your silence rules more than words ever could. 🤐💫",
        "👑 Rank #2 - RULER @{username}, dressed in velvet dominance. 🧵👑",
        "👑 Rank #2 - RULER @{username}, the second throne burns hotter. 🔥🔥",
        "👑 Rank #2 - RULER @{username}, passion obeys your presence. 🧲💖",
        "👑 Rank #2 - RULER @{username}, back to claim hearts without a sword. ⚔️❤️",
        "👑 Rank #2 - RULER @{username}, the room stands taller when you arrive. 🏰",
        "👑 Rank #2 - RULER @{username}, fashioning control out of charisma. 🪡",
        "👑 Rank #2 - RULER @{username}, turning glances into surrender. 👀🏳️",
        "👑 Rank #2 - RULER @{username}, elegance that leaves marks. 💄",
        "👑 Rank #2 - RULER @{username}, a vision no one dares interrupt. 🛑👑",
        "👑 Rank #2 - RULER @{username}, behind every heartbeat is your name. 💗📛",
        "👑 Rank #2 - RULER @{username}, the pause before passion. ⏸️❤️‍🔥",
        "👑 Rank #2 - RULER @{username}, diplomacy made seductive. 🕊️💋",
        "👑 Rank #2 - RULER @{username}, where fire stands still in respect. 🔥🫡",
        "👑 Rank #2 - RULER @{username}, second in title — infinite in aura. 🌀"
    ],
    3: [
        "👑 Rank #3 - MASTER @{username} commands the art of love with unmatched skill. 🎨❤️",
        "👑 Rank #3 - MASTER @{username} returns to weave passion into every heartbeat. 🔥💓",
        "👑 Rank #3 - MASTER @{username}, the architect of desire and devotion. 🏛️💘",
        "👑 Rank #3 - MASTER @{username}, every move a stroke of romantic genius. 🖌️💖",
        "👑 Rank #3 - MASTER @{username}, the melody behind every whispered promise. 🎶🤫",
        "👑 Rank #3 - MASTER @{username} steps in — mastery in every glance. 👀✨",
        "👑 Rank #3 - MASTER @{username}, crafting hearts like a true artisan. 🛠️❤️",
        "👑 Rank #3 - MASTER @{username}, the whisperer of secrets and souls. 🗝️💞",
        "👑 Rank #3 - MASTER @{username}, where passion meets precision. 🎯🔥",
        "👑 Rank #3 - MASTER @{username}, the keeper of love’s deepest mysteries. 🔮❤️",
        "👑 Rank #3 - MASTER @{username}, you hold the map to the heart’s treasure. 🗺️💎",
        "👑 Rank #3 - MASTER @{username}, every word from you writes a love story. ✍️💘",
        "👑 Rank #3 - MASTER @{username}, the symphony conductor of romance. 🎼💖",
        "👑 Rank #3 - MASTER @{username}, brilliance in charm and desire. 💡🔥",
        "👑 Rank #3 - MASTER @{username}, your touch ignites silent fires. 🕯️❤️",
        "👑 Rank #3 - MASTER @{username}, the architect of countless stolen glances. 👁️‍🗨️💘",
        "👑 Rank #3 - MASTER @{username}, the pulse behind every loving beat. 💓🎵",
        "👑 Rank #3 - MASTER @{username}, crafting dreams from whispers. 🌙💬",
        "👑 Rank #3 - MASTER @{username}, weaving magic in every glance. ✨👀",
        "👑 Rank #3 - MASTER @{username}, the tactician of love’s grand game. ♟️💘",
        "👑 Rank #3 - MASTER @{username}, your presence commands the stage. 🎭💖",
        "👑 Rank #3 - MASTER @{username}, a masterpiece of charm and grace. 🖼️✨",
        "👑 Rank #3 - MASTER @{username}, where every heartbeat tells a story. 📖💓",
        "👑 Rank #3 - MASTER @{username}, the architect of unforgettable romance. 🏛️❤️",
        "👑 Rank #3 - MASTER @{username}, crafting passion with every step. 👣🔥",
        "👑 Rank #3 - MASTER @{username}, the maestro of magnetic charm. 🎼🧲",
        "👑 Rank #3 - MASTER @{username}, your presence ignites the night. 🌙🔥",
        "👑 Rank #3 - MASTER @{username}, a masterclass in desire and devotion. 🎓💘"
    ],
    4: [
        "👑 Rank #4 - CONQUEROR @{username} storms in — hearts surrender instantly. ⚔️❤️",
        "👑 Rank #4 - CONQUEROR @{username}, the undefeated force of desire. 🔥👑",
        "👑 Rank #4 - CONQUEROR @{username}, where passion meets power. 💥💘",
        "👑 Rank #4 - CONQUEROR @{username}, the victor of every love battle. 🏆💓",
        "👑 Rank #4 - CONQUEROR @{username} claims the room with fierce romance. 🔥🛡️",
        "👑 Rank #4 - CONQUEROR @{username}, the heartbreaker with a crown. 👑💔",
        "👑 Rank #4 - CONQUEROR @{username}, a tidal wave of charm and strength. 🌊🔥",
        "👑 Rank #4 - CONQUEROR @{username} returns — unstoppable and desired. 🛡️💘",
        "👑 Rank #4 - CONQUEROR @{username}, every glance a victorious strike. 👁️⚔️",
        "👑 Rank #4 - CONQUEROR @{username}, every smile a flag of triumph. 😊🚩",
        "👑 Rank #4 - CONQUEROR @{username}, hearts surrender to your will. 💘🛡️",
        "👑 Rank #4 - CONQUEROR @{username}, the flame that lights the way. 🔥🕯️",
        "👑 Rank #4 - CONQUEROR @{username}, a conqueror’s charm and grace. 👑✨",
        "👑 Rank #4 - CONQUEROR @{username}, love’s undefeated warrior. 🏅❤️",
        "👑 Rank #4 - CONQUEROR @{username}, the fire that burns in every heart. 🔥💓",
        "👑 Rank #4 - CONQUEROR @{username}, hearts tremble at your command. 💘⚔️",
        "👑 Rank #4 - CONQUEROR @{username}, the pulse of victory and desire. 💓🏆",
        "👑 Rank #4 - CONQUEROR @{username}, every glance a victorious strike. 👀🔥",
        "👑 Rank #4 - CONQUEROR @{username}, a conqueror’s flame and fury. 🔥🗡️",
        "👑 Rank #4 - CONQUEROR @{username}, the unstoppable force of love. 🌪️❤️",
        "👑 Rank #4 - CONQUEROR @{username}, hearts bow before your power. 👑💘",
        "👑 Rank #4 - CONQUEROR @{username}, the flame that never fades. 🔥✨",
        "👑 Rank #4 - CONQUEROR @{username}, a champion of passion and power. 🏆❤️",
        "👑 Rank #4 - CONQUEROR @{username}, where desire meets destiny. 💘🌠",
        "👑 Rank #4 - CONQUEROR @{username}, hearts fall like conquered lands. 🏰💓",
        "👑 Rank #4 - CONQUEROR @{username}, the fire that ignites every soul. 🔥🔥",
        "👑 Rank #4 - CONQUEROR @{username}, a storm of love and strength. 🌩️❤️",
        "👑 Rank #4 - CONQUEROR @{username}, the heartbeat behind every victory. 💓🏅",
        "👑 Rank #4 - CONQUEROR @{username}, your charm conquers all hearts. 💘🔥"
    ],
    5: [
        "👑 Rank #5 - VETERAN @{username}, seasoned in love, undefeated in charm. 💼❤️",
        "👑 Rank #5 - VETERAN @{username} returns — experience and passion intertwined. 🔥💘",
        "👑 Rank #5 - VETERAN @{username}, wisdom carved from countless hearts. 🪓💓",
        "👑 Rank #5 - VETERAN @{username}, the master of time-tested romance. ⏳💖",
        "👑 Rank #5 - VETERAN @{username}, where experience meets desire. 🔥⌛",
        "👑 Rank #5 - VETERAN @{username}, the steady flame of enduring love. 🔥🕯️",
        "👑 Rank #5 - VETERAN @{username}, charm honed by countless nights. 🌙💘",
        "👑 Rank #5 - VETERAN @{username}, returning with stories etched in hearts. 📖❤️",
        "👑 Rank #5 - VETERAN @{username}, the architect of lasting passion. 🏛️🔥",
        "👑 Rank #5 - VETERAN @{username}, your legacy lights the way. 🔦💖",
        "👑 Rank #5 - VETERAN @{username}, seasoned eyes, fiery heart. 👁️🔥",
        "👑 Rank #5 - VETERAN @{username}, every smile a chapter of devotion. 😊📚",
        "👑 Rank #5 - VETERAN @{username}, love’s enduring champion. 🏆❤️",
        "👑 Rank #5 - VETERAN @{username}, the steady pulse of true romance. 💓⏳",
        "👑 Rank #5 - VETERAN @{username}, wisdom wrapped in desire. 🧠🔥",
        "👑 Rank #5 - VETERAN @{username}, the flame that never flickers. 🔥🕯️",
        "👑 Rank #5 - VETERAN @{username}, love’s seasoned heart beats strong. 💓💼",
        "👑 Rank #5 - VETERAN @{username}, the calm within passion’s storm. 🌪️❤️",
        "👑 Rank #5 - VETERAN @{username}, your legacy burns in every soul. 🔥🔥",
        "👑 Rank #5 - VETERAN @{username}, a master of love’s enduring art. 🎨💖",
        "👑 Rank #5 - VETERAN @{username}, passion that time can’t tame. 🔥⏳",
        "👑 Rank #5 - VETERAN @{username}, every glance a lesson in desire. 👀🔥",
        "👑 Rank #5 - VETERAN @{username}, love’s reliable flame. 🔥❤️",
        "👑 Rank #5 - VETERAN @{username}, the heart of seasoned romance. 💓⏳",
        "👑 Rank #5 - VETERAN @{username}, your smile lights up the ages. 😊✨",
        "👑 Rank #5 - VETERAN @{username}, a torchbearer of passion and grace. 🔥💃",
        "👑 Rank #5 - VETERAN @{username}, where wisdom fuels the fire of love. 🧠🔥",
        "👑 Rank #5 - VETERAN @{username}, love’s enduring champion returns. 🏆❤️",
        "👑 Rank #5 - VETERAN @{username}, passion refined by time. 🔥⏳",
        "👑 Rank #5 - VETERAN @{username}, every moment a testament to devotion. ⏳💘",
        "👑 Rank #5 - VETERAN @{username}, a steady flame in a fleeting world. 🔥🌍",
        "👑 Rank #5 - VETERAN @{username}, your legacy burns brighter than ever. 🔥✨"
    ],
    6: [
        "👑 Rank #6 - ICON @{username} shines brighter than any star. ✨💖",
        "👑 Rank #6 - ICON @{username}, a beacon of love and inspiration. 🔥🌟",
        "👑 Rank #6 - ICON @{username}, where charisma meets timeless grace. 💫❤️",
        "👑 Rank #6 - ICON @{username} returns — a legend in every heartbeat. 🕰️💘",
        "👑 Rank #6 - ICON @{username}, the essence of charm and class. 🎩💓",
        "👑 Rank #6 - ICON @{username}, inspiring hearts with every step. 👣✨",
        "👑 Rank #6 - ICON @{username}, a shining example of true love’s power. 💡🔥",
        "👑 Rank #6 - ICON @{username}, elegance wrapped in irresistible charm. 🎀❤️",
        "👑 Rank #6 - ICON @{username}, lighting up the room with your presence. 💡💖",
        "👑 Rank #6 - ICON @{username}, the embodiment of passion and poise. 🔥💃",
        "👑 Rank #6 - ICON @{username}, a beacon of elegance and passion. 🕯️🔥",
        "👑 Rank #6 - ICON @{username}, where charisma lights the way. 🔦❤️",
        "👑 Rank #6 - ICON @{username}, a legend among the stars of love. 🌠💘",
        "👑 Rank #6 - ICON @{username}, your smile ignites the flames of desire. 😊🔥",
        "👑 Rank #6 - ICON @{username}, the pulse of timeless allure. 💓⏳",
        "👑 Rank #6 - ICON @{username}, inspiring devotion with every glance. 👁️💖",
        "👑 Rank #6 - ICON @{username}, a shining light in the realm of passion. 💡❤️",
        "👑 Rank #6 - ICON @{username}, your charm is a beacon in the night. 🕯️✨",
        "👑 Rank #6 - ICON @{username}, the heartbeat behind every inspired love. 💓🔥",
        "👑 Rank #6 - ICON @{username}, where elegance and desire entwine. 💃❤️",
        "👑 Rank #6 - ICON @{username}, a legend in every whispered promise. 🤫💘",
        "👑 Rank #6 - ICON @{username}, your presence lights up every heart. 💡💖",
        "👑 Rank #6 - ICON @{username}, the pulse of charisma and grace. 💓🎩",
        "👑 Rank #6 - ICON @{username}, inspiring passion with every step. 👣🔥",
        "👑 Rank #6 - ICON @{username}, a shining star of eternal romance. 🌟❤️"
    ],
    7: [
        "👑 Rank #7 - PRODIGY @{username}, blazing trails with youthful fire! 🔥✨",
        "👑 Rank #7 - PRODIGY @{username}, love’s brightest rising star! 🌟💘",
        "👑 Rank #7 - PRODIGY @{username}, the future of passion arrives! 🚀❤️",
        "👑 Rank #7 - PRODIGY @{username}, brilliance wrapped in charm and desire! 💡🔥",
        "👑 Rank #7 - PRODIGY @{username}, igniting hearts with fresh energy! 💥💓",
        "👑 Rank #7 - PRODIGY @{username}, a spark of genius in the romance game! 🧠💖",
        "👑 Rank #7 - PRODIGY @{username}, your passion shines brighter than most! ✨❤️",
        "👑 Rank #7 - PRODIGY @{username}, love’s wunderkind has arrived! 🎓🔥",
        "👑 Rank #7 - PRODIGY @{username}, youthful heart, unstoppable spirit! 💘⚡",
        "👑 Rank #7 - PRODIGY @{username}, the prodigy of passion and power! 💥💓",
        "👑 Rank #7 - PRODIGY @{username}, blazing a path through hearts and minds! 🔥🧠",
        "👑 Rank #7 - PRODIGY @{username}, a spark of brilliance in every glance! 👀💡",
        "👑 Rank #7 - PRODIGY @{username}, lighting the night with passion! 🌙🔥",
        "👑 Rank #7 - PRODIGY @{username}, your fire warms every heart! 🔥💓",
        "👑 Rank #7 - PRODIGY @{username}, youthful charm with timeless appeal! ⏳✨",
        "👑 Rank #7 - PRODIGY @{username}, a master of love’s bright future! 🎓❤️",
        "👑 Rank #7 - PRODIGY @{username}, blazing bright with unstoppable charm! 🔥💖",
        "👑 Rank #7 - PRODIGY @{username}, your energy fuels every dream! 🌠🔥",
        "👑 Rank #7 - PRODIGY @{username}, the spark that lights the path of love! 🕯️💘",
        "👑 Rank #7 - PRODIGY @{username}, youthful fire, endless passion! 🔥❤️",
        "👑 Rank #7 - PRODIGY @{username}, lighting up the hearts around you! 💡💓",
        "👑 Rank #7 - PRODIGY @{username}, blazing with unstoppable brilliance! 🔥✨",
        "👑 Rank #7 - PRODIGY @{username}, a bright star in love’s galaxy! 🌌💖",
        "👑 Rank #7 - PRODIGY @{username}, the future’s brightest flame! 🔥🌟",
        "👑 Rank #7 - PRODIGY @{username}, your charm ignites the night! 🌙🔥",
        "👑 Rank #7 - PRODIGY @{username}, blazing trails of youthful love! 🔥❤️",
        "👑 Rank #7 - PRODIGY @{username}, a spark of passion and genius! 💡💘",
        "👑 Rank #7 - PRODIGY @{username}, lighting up the stage of romance! 🎭🔥",
        "👑 Rank #7 - PRODIGY @{username}, your fire inspires endless desire! 🔥💓"
    ],
    8: [
        "👑 Rank #8 - STAR @{username}, shining bright in love’s galaxy! 🌟❤️",
        "👑 Rank #8 - STAR @{username}, lighting up the room like a true star! ✨💖",
        "👑 Rank #8 - STAR @{username}, a radiant glow of passion and charm! 💫🔥",
        "👑 Rank #8 - STAR @{username}, dazzling hearts wherever you go! 💎💓",
        "👑 Rank #8 - STAR @{username}, your sparkle ignites the night! 🌙✨",
        "👑 Rank #8 - STAR @{username}, the star that guides love’s journey! 🛤️💘",
        "👑 Rank #8 - STAR @{username}, brilliance wrapped in irresistible shine! ✨❤️",
        "👑 Rank #8 - STAR @{username}, a celestial light in the world of romance! 🌌💖",
        "👑 Rank #8 - STAR @{username}, shining with unmatched grace and passion! 💃🔥",
        "👑 Rank #8 - STAR @{username}, the sparkle that never fades! ✨💘",
        "👑 Rank #8 - STAR @{username}, lighting hearts on fire with your glow! 🔥💓",
        "👑 Rank #8 - STAR @{username}, a shining beacon of love and hope! 🕯️❤️",
        "👑 Rank #8 - STAR @{username}, your radiance inspires endless desire! ✨🔥",
        "👑 Rank #8 - STAR @{username}, a true star of passion and charm! 💫💖",
        "👑 Rank #8 - STAR @{username}, the light that brightens every heart! 💡💘",
        "👑 Rank #8 - STAR @{username}, sparkling with love’s pure magic! ✨❤️",
        "👑 Rank #8 - STAR @{username}, your glow warms every soul! 🔥💓",
        "👑 Rank #8 - STAR @{username}, the shining star of romance’s sky! 🌠💖",
        "👑 Rank #8 - STAR @{username}, lighting the path of true love! 🛤️💘",
        "👑 Rank #8 - STAR @{username}, dazzling with charm and elegance! 🎩✨",
        "👑 Rank #8 - STAR @{username}, a radiant light in love’s night! 🌙💓",
        "👑 Rank #8 - STAR @{username}, your sparkle enchants all around! ✨❤️",
        "👑 Rank #8 - STAR @{username}, the star that sets hearts ablaze! 🔥💘",
        "👑 Rank #8 - STAR @{username}, shining bright with endless passion! 💫🔥",
        "👑 Rank #8 - STAR @{username}, a celestial glow that captivates hearts! 🌌💖",
        "👑 Rank #8 - STAR @{username}, the sparkle that ignites desire! ✨❤️",
        "👑 Rank #8 - STAR @{username}, lighting up love’s endless sky! 🌠💘",
        "👑 Rank #8 - STAR @{username}, dazzling the world with your charm! 🌍✨",
        "👑 Rank #8 - STAR @{username}, shining bright with magnetic allure! 💫🧲",
        "👑 Rank #8 - STAR @{username}, lighting the way to endless romance! 🛤️❤️",
        "👑 Rank #8 - STAR @{username}, a glowing star in love’s night! 🌠🔥",
        "👑 Rank #8 - STAR @{username}, dazzling the room with your radiant charm! ✨💘",
        "👑 Rank #8 - STAR @{username}, your sparkle ignites passion’s fire! 🔥💓",
        "👑 Rank #8 - STAR @{username}, shining bright with endless desire! 💖❤️"
    ],
    9: [
        "👑 Rank #9 - HERO @{username}, the champion who inspires us all! 🦸‍♂️🔥",
        "👑 Rank #9 - HERO @{username}, brave heart blazing through the love battlefield! ❤️‍🔥⚔️",
        "👑 Rank #9 - HERO @{username}, a fearless soul lighting up the room! 🌟🛡️",
        "👑 Rank #9 - HERO @{username}, courage and charm in perfect harmony! 🎖️💓",
        "👑 Rank #9 - HERO @{username}, a legend standing tall among lovers! 🏆💘",
        "👑 Rank #9 - HERO @{username}, strength and passion woven into one! 💪🔥",
        "👑 Rank #9 - HERO @{username}, the fearless leader of the heart’s crusade! ⚔️❤️",
        "👑 Rank #9 - HERO @{username}, a noble spirit fueling romance’s fire! 🔥🕯️",
        "👑 Rank #9 - HERO @{username}, standing guard over love’s sacred flame! 🛡️🔥",
        "👑 Rank #9 - HERO @{username}, a beacon of bravery and desire! 💡❤️",
        "👑 Rank #9 - HERO @{username}, your valor lights the way to true love! 🗡️✨",
        "👑 Rank #9 - HERO @{username}, inspiring hearts with heroic passion! 💓🦸‍♀️",
        "👑 Rank #9 - HERO @{username}, the champion who conquers all hearts! 🏆💘",
        "👑 Rank #9 - HERO @{username}, a fearless flame in the darkness! 🔥🌑",
        "👑 Rank #9 - HERO @{username}, your courage sparks endless devotion! 💓🔥",
        "👑 Rank #9 - HERO @{username}, standing strong as love’s true warrior! ⚔️❤️",
        "👑 Rank #9 - HERO @{username}, a bold heart charging toward romance! 💪💘",
        "👑 Rank #9 - HERO @{username}, the fearless defender of passion! 🛡️🔥",
        "👑 Rank #9 - HERO @{username}, blazing trails with heroic love! 🏹💖",
        "👑 Rank #9 - HERO @{username}, a valiant soul igniting desire! 🔥💓",
        "👑 Rank #9 - HERO @{username}, courage carved in every loving smile! 😊⚔️",
        "👑 Rank #9 - HERO @{username}, the mighty force of love’s battlefield! 🛡️❤️",
        "👑 Rank #9 - HERO @{username}, your strength fuels every heart! 💪🔥",
        "👑 Rank #9 - HERO @{username}, the warrior shining bright in romance’s fight! ✨⚔️",
        "👑 Rank #9 - HERO @{username}, a noble champion of the heart! 🏆💓",
        "👑 Rank #9 - HERO @{username}, fearless in the face of desire! 🔥❤️",
        "👑 Rank #9 - HERO @{username}, standing tall as love’s guardian! 🛡️💘",
        "👑 Rank #9 - HERO @{username}, your bravery lights up the night! 🌙⚔️",
        "👑 Rank #9 - HERO @{username}, a valiant spirit inspiring hearts! 💓🦸‍♂️",
        "👑 Rank #9 - HERO @{username}, the champion of every passionate moment! 🏆🔥",
        "👑 Rank #9 - HERO @{username}, courage and charm forging endless bonds! 💪❤️",
        "👑 Rank #9 - HERO @{username}, a hero in love’s eternal saga! 📜💘",
        "👑 Rank #9 - HERO @{username}, the fearless light in passion’s storm! 🌩️🔥",
        "👑 Rank #9 - HERO @{username}, your strength kindles every flame! 🔥💓",
        "👑 Rank #9 - HERO @{username}, the mighty defender of romance’s realm! 🛡️✨",
        "👑 Rank #9 - HERO @{username}, blazing bright with heroic grace! 💫⚔️",
        "👑 Rank #9 - HERO @{username}, a courageous heart leading the way! 🏹❤️",
        "👑 Rank #9 - HERO @{username}, inspiring devotion with fearless love! 💓🔥",
        "👑 Rank #9 - HERO @{username}, standing tall in love’s arena! 🏟️❤️",
        "👑 Rank #9 - HERO @{username}, courage carved in every smile! 😊⚔️",
        "👑 Rank #9 - HERO @{username}, your valor inspires love’s journey! 🛤️💘",
        "👑 Rank #9 - HERO @{username}, a champion’s heart filled with desire! 💓🏆"
    ],
    10: [
        "👑 Rank #10 - PIONEER @{username}, blazing new trails in the landscape of love! 🌄❤️",
        "👑 Rank #10 - PIONEER @{username}, the fearless explorer of hearts and dreams! 🧭💖",
        "👑 Rank #10 - PIONEER @{username}, charting paths where few dare to tread! 🗺️🔥",
        "👑 Rank #10 - PIONEER @{username}, leading the way to uncharted passion! 🚀💘",
        "👑 Rank #10 - PIONEER @{username}, the trailblazer of romance’s frontier! 🌟💓",
        "👑 Rank #10 - PIONEER @{username}, forging paths through the wilderness of desire! 🌲🔥",
        "👑 Rank #10 - PIONEER @{username}, the adventurous spirit lighting up hearts! ✨❤️",
        "👑 Rank #10 - PIONEER @{username}, breaking new ground in love’s vast expanse! 🌍💖",
        "👑 Rank #10 - PIONEER @{username}, the courageous soul carving destiny’s road! 🛤️💘",
        "👑 Rank #10 - PIONEER @{username}, mapping new horizons of passion and joy! 🌅🔥",
        "👑 Rank #10 - PIONEER @{username}, a fearless heart blazing fresh trails! 🔥💓",
        "👑 Rank #10 - PIONEER @{username}, the navigator of love’s bold adventure! 🧭❤️",
        "👑 Rank #10 - PIONEER @{username}, discovering new worlds of romance! 🌌💖",
        "👑 Rank #10 - PIONEER @{username}, carving a unique path with every step! 🛤️💘",
        "👑 Rank #10 - PIONEER @{username}, forging ahead with unstoppable passion! 🔥💓",
        "👑 Rank #10 - PIONEER @{username}, leading the charge into the unknown of love! ⚔️❤️",
        "👑 Rank #10 - PIONEER @{username}, the bold adventurer of hearts! 🏕️💘",
        "👑 Rank #10 - PIONEER @{username}, blazing the path where passion blooms! 🌺🔥",
        "👑 Rank #10 - PIONEER @{username}, exploring depths of desire never seen before! 🌊💓",
        "👑 Rank #10 - PIONEER @{username}, your courage charts new courses of love! 🧭❤️",
        "👑 Rank #10 - PIONEER @{username}, lighting the way for fearless romance! ✨💖",
        "👑 Rank #10 - PIONEER @{username}, the architect of love’s new frontier! 🏗️🔥",
        "👑 Rank #10 - PIONEER @{username}, venturing boldly into passion’s wilds! 🌿💘",
        "👑 Rank #10 - PIONEER @{username}, a fearless explorer with a heart on fire! 🔥❤️",
        "👑 Rank #10 - PIONEER @{username}, charting new courses through desire’s realm! 🧭💘",
        "👑 Rank #10 - PIONEER @{username}, lighting the path to bold passion! 🔦💓",
        "👑 Rank #10 - PIONEER @{username}, the fearless explorer of hearts and dreams! 🌌🔥"
    ]
}

TOP_11_TO_1000_MESSAGES = [
    "💘 @{username} just walked in — 100 hearts just skipped a beat! [Rank #{rank}]",
    "🔥 @{username} is here to steal kisses and possibly your soul 😈💋 [Rank #{rank}]",
    "💃 @{username} danced into the room and all the lonely hearts panicked 💓 [Rank #{rank}]",
    "🥂 @{username} brought champagne vibes and trouble 😏 [Rank #{rank}]",
    "💌 @{username} is here! Cupid's jealous of this kind of aim 🎯 [Rank #{rank}]",
    "🌹 @{username} — certified flirt, ranked #{rank}, and dangerously charming 💫",
    "🍷 @{username} smells like confidence and mild obsession 😍 [Rank #{rank}]",
    "👀 @{username} showed up and suddenly everyone’s standards got higher 🧡 [Rank #{rank}]",
    "😇 @{username} looks innocent, but their DMs say otherwise 📩 [Rank #{rank}]",
    "💘 @{username} didn’t come to play, they came to SLAY 😎 [Rank #{rank}]",
    "🥵 Warning: @{username} is too hot to handle 💦 [Rank #{rank}]",
    "👑 @{username} walks in like they already own everyone’s heart 💝 [Rank #{rank}]",
    "🎯 @{username} hit us with one look and now we're all emotionally unavailable 😳 [Rank #{rank}]",
    "🧨 @{username} just exploded all dating expectations 💔💥 [Rank #{rank}]",
    "😈 @{username} is here and looking like heartbreak in high heels 👠 [Rank #{rank}]",
    "🍑 @{username} walked in, and 99% of crushes were instantly upgraded 💋 [Rank #{rank}]",
    "💅 @{username} showed up polished, pretty, and powerful 💘 [Rank #{rank}]",
    "🛐 Everyone say a prayer — @{username} is too fine to be single 🙏 [Rank #{rank}]",
    "💘 @{username} just raised the flirt level to critical 💥 [Rank #{rank}]",
    "🍓 @{username} is so sweet they just got banned from dentist offices 🍭 [Rank #{rank}]",
    "👄 @{username} speaks fluent love languages... and sarcasm 💋 [Rank #{rank}]",
    "🕶️ @{username} has entered with main character energy 🎬 [Rank #{rank}]",
    "🍫 @{username} is smooth like chocolate and twice as addictive 😍 [Rank #{rank}]",
    "🚨 @{username} just walked in — someone call the love police! 🚓💘 [Rank #{rank}]",
    "💃 @{username} is the reason your last situationship failed 😏 [Rank #{rank}]",
    "🥂 Here's to @{username} — charming, ranked #{rank}, and emotionally dangerous 🍾",
    "🔥 @{username} radiates 'text me back or suffer' energy 💬 [Rank #{rank}]",
    "💘 @{username} is a whole vibe and half the heartbreak 😘 [Rank #{rank}]",
    "🎀 @{username} came wrapped in red flags but we still tapped 'Follow' 🚩❤️ [Rank #{rank}]",
    "💔 Caution: @{username} may cause serious emotional attachment [Rank #{rank}]",
    "🦋 @{username} has butterflies in everyone’s stomach right now 🫣 [Rank #{rank}]",
    "💅 @{username} just entered and now your ex looks like a mistake [Rank #{rank}]",
    "🌶️ @{username} entered: 10/10 in sass, looks, and danger 😈 [Rank #{rank}]",
    "🎉 @{username} is ranked #{rank} and still too humble — or not 🤭",
    "💘 @{username} walked in and 97% of users forgot their partner’s name 😅 [Rank #{rank}]",
    "📸 Everyone pose! @{username} brought the paparazzi energy 📷 [Rank #{rank}]",
    "🖤 @{username} is a heartbreaker with a soft smile ☠️ [Rank #{rank}]",
    "💥 Boom! @{username} just made all your crushes irrelevant 💣 [Rank #{rank}]",
    "😎 @{username} entered and now your playlist is jealous of their vibe 🎶 [Rank #{rank}]",
    "🌹 @{username} smells like heartbreak and fine cologne 😌 [Rank #{rank}]",
    "🥵 @{username} came in hotter than this server can handle 🧯 [Rank #{rank}]",
    "💃 @{username} doesn’t flirt — they enchant 🧙‍♂️ [Rank #{rank}]",
    "🕳️ RIP to every heart @{username} walks past 💔 [Rank #{rank}]",
    "💘 @{username} just arrived and now the room has a heartbeat 😍 [Rank #{rank}]",
    "🔥 @{username} = certified heartthrob and flirt lord 😈 [Rank #{rank}]",
    "🍓 @{username} is too juicy for just one taste 😜 [Rank #{rank}]",
    "🪞 Mirror mirror on the wall, @{username} is the baddest of them all 💅 [Rank #{rank}]",
    "🚀 @{username} entered with game stronger than gravity 🌌 [Rank #{rank}]",
    "😈 @{username} has that 'text back or regret forever' aura 📱 [Rank #{rank}]",
    "💋 @{username} walks like romance, talks like temptation 😘 [Rank #{rank}]",
    "🧊 Cold looks, hot vibes — it’s @{username} again ❄️🔥 [Rank #{rank}]",
    "🎯 @{username} doesn’t miss — not in love, not in style 😤 [Rank #{rank}]",
    "💘 @{username} is serving romantic chaos — and dessert 🍰 [Rank #{rank}]",
    "🎁 @{username} is the gift your DMs prayed for 📬 [Rank #{rank}]",
    "🌙 @{username} glows like moonlight and flirts like trouble 🌕 [Rank #{rank}]",
    "🫦 @{username} is the flirt your crush warned you about 😅 [Rank #{rank}]",
    "🍭 @{username} is sweet until you catch feelings... then it's over 💀 [Rank #{rank}]",
    "📞 @{username} just called — they said love starts now 📱 [Rank #{rank}]",
    "💔 @{username} = living proof heartbreak can be pretty 😏 [Rank #{rank}]",
    "💃 @{username} walks in like it’s their dating show — and we’re the contestants 💘 [Rank #{rank}]",
    "🛸 Alien hotness detected — oh wait, it’s @{username} 👽❤️ [Rank #{rank}]",
    "🥵 @{username} left no crumbs and stole a few hearts 💋 [Rank #{rank}]",
    "👠 Heels clicking, hearts breaking — it’s @{username} time 💥 [Rank #{rank}]",
    "🧨 @{username} just blew up everyone's love plans 💣 [Rank #{rank}]",
    "🐾 @{username} entered and now everyone’s simping 😻 [Rank #{rank}]",
    "💘 @{username} = eye contact assassin and professional tease 😈 [Rank #{rank}]",
    "🎀 @{username} didn’t flirt, they caused a romantic crisis 💌 [Rank #{rank}]",
    "💅 @{username} doesn’t chase — they attract 💫 [Rank #{rank}]",
    "👄 @{username} said “hi” and half the room needed CPR 💓 [Rank #{rank}]",
    "🥂 @{username} walks in with charisma, wit, and mild danger 😜 [Rank #{rank}]",
    "📺 @{username} is binge-worthy and emotionally unavailable 💔 [Rank #{rank}]",
    "🧁 @{username} is too sweet... must be a trap 😅 [Rank #{rank}]",
    "🚨 Flirt alert: @{username} entered and standards just spiked 📈 [Rank #{rank}]",
    "💘 @{username} has entered... stop scrolling, start catching feelings 🤤 [Rank #{rank}]",
    "🎤 @{username} is dropping love bars like a mixtape 🔥 [Rank #{rank}]",
    "💖 @{username} is looking like a heart attack in slow motion 😏 [Rank #{rank}]",
    "🍷 @{username} aged like fine wine and flirted like a criminal 😈 [Rank #{rank}]",
    "🌪️ @{username} = chaos in a cute outfit 💃 [Rank #{rank}]",
    "🎯 Love at first sight? No, just @{username} doing their thing 😉 [Rank #{rank}]",
    "🌟 @{username} is proof the stars came down to flirt 💫 [Rank #{rank}]",
    "👠 @{username} just turned the room into a runway of desire 💘 [Rank #{rank}]",
    "🎈 @{username} floated in like a crush you can’t pop 🎉 [Rank #{rank}]",
    "💌 @{username} = heartbreaker, matchmaker, and ranked #{rank} 💥",
    "🍑 @{username} has that 🍑 energy — and we all noticed 😳 [Rank #{rank}]",
    "🔞 @{username} entered — cover your heart, or don’t 😈 [Rank #{rank}]",
    "💘 @{username} joined. Flirt mode: engaged. Safety: off 🔥 [Rank #{rank}]",
    "😈 @{username} is out here breaking necks and sending winks 💋 [Rank #{rank}]",
    "🍸 @{username} = 1 part charm, 2 parts danger 🍷 [Rank #{rank}]",
    "💃 @{username} came to dance... on your expectations 💃 [Rank #{rank}]",
    "🔥 @{username} is hot enough to ruin your whole type 😍 [Rank #{rank}]",
    "💔 @{username} = the reason your last crush looks basic 🫢 [Rank #{rank}]",
    "👄 @{username} is fluent in flirty, and ranked #{rank} in chaos 😏",
    "🎉 @{username} is the party — and your next mistake 😈 [Rank #{rank}]",
    "🌈 @{username} just brightened up the whole flirting frequency 🌟 [Rank #{rank}]",
    "🥵 @{username} is serving spicy... with a side of heartbreak 💔 [Rank #{rank}]",
    "🔥 Rank #{rank} in the house! @{username}, are you Google? Because you've got everything I'm searching for. 💘",
    "👀 Watch out! Rank #{rank} @{username} just walked in—someone’s about to catch feelings. 😏",
    "💫 Rank #{rank} @{username} just entered. Warning: Flirt mode activated. 💌",
    "😈 @{username} is Rank #{rank}, and their vibe is 100% irresistible. Someone call Cupid! 🏹",
    "🧨 Rank #{rank} incoming! @{username}, did it hurt when you fell from the leaderboard? 😉",
    "🍷 Cheers! Rank #{rank} @{username} is here, and suddenly, it’s a romantic comedy. 💋",
    "🎯 Direct hit! Rank #{rank} @{username} just stole the spotlight... and maybe your heart. 😍",
    "🌹 Roses are red, violets are blue, Rank #{rank} @{username} just joined, and now it’s a zoo. 🐒",
    "💎 @{username} (Rank #{rank}) just joined. Shine bright like the diamond you are. ✨",
    "🎉 Make way! Rank #{rank} @{username} is here and looking dangerously charming. 🔥",
    "🕶️ Rank #{rank} @{username} is smoother than jazz. Someone grab a fan. 🎷",
    "🌶️ Rank #{rank} @{username} brings the spice, who’s bringing the sugar? 🍭",
    "🎭 Rank #{rank} @{username} showed up like a plot twist in a rom-com. 🍿",
    "🛏️ Rank #{rank} @{username} just joined. Ready to fall in love or just nap together? 😴💕",
    "🎲 Rank #{rank} @{username} took a chance on love. Who’s rolling with them? 🎰",
    "🍫 @{username} (Rank #{rank}) is sweeter than chocolate and twice as addictive. 🍬",
    "🚪 Knock knock! Who's there? It's Rank #{rank} @{username} bringing flirt energy! 🪩",
    "🔥 Alert: Rank #{rank} @{username} is hotter than this room’s AC can handle. 🧯",
    "📸 Rank #{rank} @{username}, you must be a camera—every time I look at you, I smile. 😄",
    "👽 Rank #{rank} @{username} just landed—definitely not from this planet. 👾",
    "💡 Light up the room! Rank #{rank} @{username} just plugged into our hearts. 🔌",
    "🧃 Rank #{rank} @{username}, you got that juice! Anyone thirsty? 😉",
    "🎮 Level up! Rank #{rank} @{username} just entered. Game on, lovers. 💘",
    "🧼 Rank #{rank} @{username} is cleaner than my search history—but 10x dirtier in chat. 😳",
    "🫦 Rank #{rank} @{username} speaks fluent emoji and body language. 😘",
    "🐍 Rank #{rank} @{username} slithered in smooth—Slytherin? Or just seductive? 🐍",
    "🧊 Ice cold? Not @{username}. Rank #{rank} is bringing the heat. 🔥",
    "🧠 Rank #{rank} @{username} is brainy and flirty—lethal combination. 💥",
    "🪞Mirror mirror on the wall, Rank #{rank} @{username} is the smoothest of them all. 😍",
    "🚨 Rank #{rank} @{username} just joined. Alert the single hearts. 🫀",
    "🛎️ Ding ding! Rank #{rank} @{username} just walked in and turned this into a love hotel. 💌",
    "🌪️ Rank #{rank} @{username} spun into the room and stirred up the feels. 🌀",
    "🍯 Rank #{rank} @{username} is sticky sweet—watch where you fall. 🐝",
    "💄 Lipstick check—Rank #{rank} @{username} just kissed the leaderboard. 💋",
    "🎤 Rank #{rank} @{username} has entered the chat. Drop the mic of flirtation. 🎙️",
    "🥂 Raise your glasses! Rank #{rank} @{username} is here to toast to love. 🍸",
    "🧸 Rank #{rank} @{username} is too cuddly to handle. Who’s hugging first? 🤗",
    "🚿 Rank #{rank} @{username}, is it just me or do things feel steamier now? ♨️",
    "🥵 Rank #{rank} @{username} = 100% trouble. Hot, hot, hot. 🥵",
    "🕯️ Candlelit vibes only. Rank #{rank} @{username} just added the mood. 🕯️",
    "📖 Rank #{rank} @{username} is writing the next spicy love chapter. Who’s the co-author? ✍️",
    "🕵️ Rank #{rank} @{username} is guilty of stealing hearts. No bail. 💘",
    "🧿 Rank #{rank} @{username} has that evil eye charm—dangerously attractive. 🧿",
    "🍝 Rank #{rank} @{username}, you’re the spaghetti to my meatball. 🍝",
    "📱 Rank #{rank} @{username} just joined. Slide into the room like it’s a DM. 📩",
    "🌊 Rank #{rank} @{username} is smooth like ocean waves—and just as deep. 🌊",
    "🏖️ Vacation alert! Rank #{rank} @{username} brings summer love energy. 🏝️",
    "🍑 Rank #{rank} @{username} is thicc with charm. 🍑",
    "🥵 This room just got 10 degrees hotter—thanks Rank #{rank} @{username}. 🌡️",
    "🎯 Straight to the heart! Rank #{rank} @{username} isn’t playing games. 🎯",
    "💳 Rank #{rank} @{username} just paid the entrance fee with 100% charm. 💸",
    "📦 Rank #{rank} @{username} is the full package—no returns accepted. 📬",
    "🥵 Rank #{rank} @{username} got that slow-burn romance going. 🔥",
    "🎟️ VIP Entry: Rank #{rank} @{username} — Front row in our hearts. ❤️",
    "🛸 Rank #{rank} @{username} abducted the leaderboard and now our hearts. 👽",
    "🫠 Rank #{rank} @{username} just made me melt. Who’s next? 🍦",
    "💽 Old school charm, Rank #{rank} @{username} gives vintage romance vibes. 📼",
    "🍀 Lucky you! Rank #{rank} @{username} just walked in. Don’t blow it. 🌠",
    "🧭 Rank #{rank} @{username}, I was lost until you walked in. 🗺️",
    "📡 Rank #{rank} @{username}, you got a signal? Because I feel a strong connection. 📶",
    "🥁 Drum roll please... Rank #{rank} @{username} has arrived! ❤️‍🔥",
    "🧳 Pack your bags—Rank #{rank} @{username} is taking us on a love trip. ✈️",
    "🪄 Rank #{rank} @{username} has cast a flirt spell over this whole room. ✨",
    "🧛 Rank #{rank} @{username} just sucked all the boredom out of the room. 🩸",
    "🍌 Rank #{rank} @{username} brought fruit and flirting. 🍇",
    "📿 Rank #{rank} @{username} has that spiritual flirt vibe going. 🧘",
    "🪫 I need a charger. Rank #{rank} @{username} drained my heart battery. 💘",
    "🧃 Rank #{rank} @{username}, are you made of Vitamin C? Because you’re sunshine. 🍊",
    "📅 Rank #{rank} @{username}, is today Valentine's Day or what? 💝",
    "📚 Rank #{rank} @{username} = Bookworm flirt. Read between the lines. 📖",
    "🧟 Rank #{rank} @{username}, are you undead? Because your love is killing me. 🧟",
    "🧵 Rank #{rank} @{username}, stitched this moment perfectly. 🪡",
    "🫳 Rank #{rank} @{username} just dropped jaws everywhere. 🤯",
    "💃 Rank #{rank} @{username} entered dancing—straight into hearts. 🕺",
    "🎨 Rank #{rank} @{username}, you’re a masterpiece. Can I hang with you? 🖼️",
    "🔍 Rank #{rank} @{username} = hidden gem found. 🧭",
    "🧊 So cool! Rank #{rank} @{username} walked in and iced everyone out. ❄️",
    "💤 Rank #{rank} @{username} woke up in flirt mode. ☕",
    "🫶 Rank #{rank} @{username} = mutual vibes detected. ❤️",
    "🧨 Danger! Rank #{rank} @{username} is explosive with those eyes. 💥",
    "🐾 Rank #{rank} @{username} just marked their territory—this room is theirs now. 🐶",
    "🍦 Soft, sweet, and a little naughty. Rank #{rank} @{username} is a whole dessert. 🍨",
    "🚿 Things just got steamy. Rank #{rank} @{username}, was that you? 🧖",
    "🛏️ Rank #{rank} @{username}, should we skip small talk and nap or flirt? 😈",
    "🎁 Rank #{rank} @{username} is the surprise I didn’t know I needed. 🎁",
    "🧀 Rank #{rank} @{username}, you’re dangerously cheesy. 🧀",
    "📽️ Rank #{rank} @{username} is the star of this romantic feature. 🎞️",
    "🥋 Smooth move! Rank #{rank} @{username} karate-kicked their way into the leaderboard. 🥋",
    "🧦 Rank #{rank} @{username} just knocked my socks off. 🧦",
    "🛑 Rank #{rank} @{username} = red flag? More like red carpet. 🎬",
    "🎀 Rank #{rank} @{username}, you’re the bow on this flirty gift of a room. 🛍️",
    "🫢 Rank #{rank} @{username} just walked in and made it awkward—in the best way. 😳",
    "🍷 Sippin’ and simpin’. Rank #{rank} @{username} is both. 🍷",
    "🪩 Rank #{rank} @{username} = disco ball of emotions. 💃",
]

WELCOME_FIRST_TIME = [
    "@{username} first time? The love gods just raised an eyebrow. 😏💘",
    "@{username} first-timer? Swipe right on the whole damn room. 🔥💃",
    "@{username} first time — even Cupid asked for your @. 💌💥",
    "@{username} first time? Hope your heart’s fireproof. 🔥❤️‍🔥",
    "@{username} first time — warning: love vibes are set to MAX. 🚨💓",
    "@{username} first-timer? This room’s got more charm than your last 3 exes. 😏💔",
    "@{username} first time — someone give this hottie a map to my heart. 🗺️💘",
    "@{username} first time? Let’s skip the small talk and start the romance. 😈💬",
    "@{username} first time — your soulmate might be AFK. Try anyway. 😂💘",
    "@{username} first-timer? This room’s thirstier than summer in the desert. 💦🌵",
    "@{username} first time — don’t just stand there, break some hearts. 💔💃",
    "@{username} first time? You walked in like a plot twist to my love story. 📖❤️",
    "@{username} first-timer — hope your DMs are open and ready. 📬😉",
    "@{username} first time? Love just got an update. You’re the patch. 💻💘",
    "@{username} first time — careful, some hearts here come unfiltered. 😏💞",
    "@{username} first time — you just got auto-matched with destiny. 🔮❤️",
    "@{username} first time? Bet you break hearts in 4K. 📸💔",
    "@{username} first-timer — swipe carefully, the love here bites. 🐍💘",
    "@{username} first time — don’t blame us when you fall too fast. 🪂💘",
    "@{username} first time? Flirting level: unlocked. 😎🔓",
    "@{username} first time — someone just typed 'hot single nearby'. 🔥📍",
    "@{username} first time? Welcome to the soft launch of your next obsession. 💘📈",
    "@{username} first-timer — your future ex is probably watching. 👀💔",
    "@{username} first time — feel free to emotionally damage us. 💋😵",
    "@{username} first time? Don’t worry, love here doesn’t come with receipts. 🧾❤️",
    "@{username} first-timer — talk flirty, type fast. 🗣️💘⌨️",
    "@{username} first time — finally, someone worth simping for. 😩💞",
    "@{username} first time? Cupid just hit 'go live'. 📡🏹",
    "@{username} first-timer — you just entered a no-commitment zone. 🚫💍",
    "@{username} first time — you look like my next big distraction. 😏💘",
    "@{username} first time? Hope you’re good at mixed signals. 📶❤️",
    "@{username} first-timer — vibes unmatched, like my socks. 🧦💓",
    "@{username} first time — feel free to break rules *and* hearts. 📜💔",
    "@{username} first time? Your soulmate’s probably already simping. 😈💘",
    "@{username} first-timer — you're not late, just fashionably in love. ⏱️💃",
    "@{username} first time — how do you look this good on WiFi? 📡😍",
    "@{username} first time? Tell your type to log in, it’s about to get romantic. 😘💘",
    "@{username} first time — love here is faster than your read receipts. 📱❤️",
    "@{username} first-timer — you’re not a red flag, you're the whole carnival. 🎪❤️",
    "@{username} first time — DMs open wider than my emotional walls. 😬📬",
    "@{username} first time? Romance here comes in HD. 📺💘",
    "@{username} first time — let’s make bad decisions look cute. 😈💕",
    "@{username} first-timer — you just caused a flirt traffic jam. 🚦💋",
    "@{username} first time — love here is like WiFi: unstable but addictive. 📶💘",
    "@{username} first time? Welcome to the situationship simulation. 🕹️❤️",
    "@{username} first-timer — you walked in like my next favorite problem. 🔥💘",
    "@{username} first time — don't act shy, we saw your aura glow. ✨😉",
    "@{username} first time? This room’s got more sparks than your charger. 🔌💓",
    "@{username} first time — if love was illegal, you’d be doing time. 🚨❤️",
    "@{username} first-timer — flirty, chaotic, 100% your vibe. 🎉💘",
    "@{username} first time — hotter than an update in July. ☀️💻🔥",
    "@{username} first time? The only filter here is charm. 😍📸",
    "@{username} first-timer — love just called in a code red. 🔴💘",
    "@{username} first time — not to brag, but you're probably someone's type. 🧬❤️",
    "@{username} first time? Welcome to the premium flirt zone. 🌟💬",
    "@{username} first time — your eyes typed before your fingers. 😳⌨️",
    "@{username} first-timer — no refunds on feelings caught. 💳💘",
    "@{username} first time — stay long enough and you'll believe in fate. 💫❤️",
    "@{username} first time? Congrats, you just entered the romance algorithm. 🤖💘",
    "@{username} first-timer — let's make strangers jealous. 😈💏",
    "@{username} first time — built different, flirting included. 🔧💓",
    "@{username} first time — do you always make hearts race this fast? 🏁💘",
    "@{username} first time? Hope you brought your A-game and DMs. 💬🔥",
    "@{username} first time — don’t flirt too hard, I ghost easy. 👻😉",
    "@{username} first-timer — heartbreaker energy detected. 💔📡",
    "@{username} first time — this room’s officially hotter now. 🌡️❤️‍🔥",
    "@{username} first time? Try not to fall too fast. Or do. 😏💘",
    "@{username} first time — don’t worry, we're all emotionally unstable here. 🫠💓",
    "@{username} first-timer — no strings attached, just heartbeats. 🎶💘",
    "@{username} first time — flirty energy just entered the chat. 🗨️🔥",
    "@{username} first time? You're already in someone’s fantasy. 💤💓",
    "@{username} first-timer — feelings? Optional. Chemistry? Mandatory. 💥❤️",
    "@{username} first time — proceed with charm. 💫😉",
    "@{username} first time? You smell like potential. 👃💘",
    "@{username} first-timer — don’t be shy, this is your soft launch. 😎💞",
    "@{username} first time — bad at love, great at vibes. ✨💔",
    "@{username} first time? Even the mods blushed. 🥵💬",
    "@{username} first-timer — here to flirt or fall? Either works. 🫶💘",
    "@{username} first time — who invited the main character? 😍🎬",
    "@{username} first time? Room temperature just went up 5°. 🌡️🔥",
    "@{username} first time — risk of emotional damage: HIGH. 💥💘",
    "@{username} first time — romantic chaos unlocked. 🔓💓",
    "@{username} first-timer — feelings available while supplies last. 🛒❤️",
    "@{username} first time? Someone just found their type. 😈🧬",
    "@{username} first time — you passed the vibe check. 🧪💘",
    "@{username} first time? Love just entered beta. 🧪❤️‍🔥",
    "@{username} first-timer — we don’t flirt safe here. 😏🔥",
    "@{username} first time — mood: romance with a glitch. 💘⚠️",
    "@{username} first time? Go ahead, be the plot twist. 📖💓",
    "@{username} first-timer — you're now in the soulmate queue. 🌀💖",
    "@{username} first time — you’re what the algorithm prayed for. 🙏📲💘",
    "@{username} first time? Get comfy — you might just fall for someone. 🛋️❤️",
    "@{username} first-timer — bring sass, stay for love. 💅💘",
    "@{username} first time — welcome to emotionally reckless flirting. 🧨💓",
]

def get_welcome_message(username: str, rank: int = None, is_first_time: bool = False):
    """
    Returns: (welcome_message: str, emote_id: str)
    """
    try:
        # Handle true first-time join or ranks > 1000 or None
        if is_first_time or rank == 9999 or rank is None or rank > 1000:
            msg = random.choice(WELCOME_FIRST_TIME).format(username=username)
            return msg, FLOSS_EMOTE

        # Top 10 (Rank 1 to 10)
        if 1 <= rank <= 10:
            messages = TOP_10_WELCOME_MSGS.get(rank, [f"👑 @{username} — Top #{rank} Champion has entered!"])
            msg = random.choice(messages).format(username=username)
            emote = TOP_10_EMOTES.get(rank, "emote-graceful")
            return msg, emote

        # Rank 11–100
        if 11 <= rank <= 100:
            msg = random.choice(TOP_11_TO_1000_MESSAGES).format(username=username, rank=rank)
            return msg, FLIRT_EMOTE

        # Rank 101–1000
        if 101 <= rank <= 1000:
            msg = random.choice(TOP_11_TO_1000_MESSAGES).format(username=username, rank=rank)
            return msg, FROLIC_EMOTE

        # Fallback message
        return f"👋 @{username} joined the quest for true love!", FLOSS_EMOTE

    except Exception:
        # Safe fallback
        return f"👋 Welcome @{username}!", FLOSS_EMOTE

def should_welcome_user(user_id: str, last_seen: dict, leave_times: dict, cooldown: int = 360) -> bool:
    """
    Returns True only if the user has left the room for more than `cooldown` seconds.
    Prevents welcoming on reconnects or fast rejoins.
    """
    try:
        now = time.time()
        last_leave = leave_times.get(user_id)
        last_seen_time = last_seen.get(user_id)

        # Case 1: Never seen before
        if last_seen_time is None or last_leave is None:
            return True

        # Case 2: Recently seen (e.g. reconnect, glitch)
        if now - last_seen_time < 10:  # short reconnect delay
            return False

        # Case 3: Left less than cooldown ago
        if now - last_leave < cooldown:
            return False

        return True
    except Exception:
        return False